export const MINT_ERROR_CODES = {
	COMBINATION_TAKEN: "COMBINATION_TAKEN",
	ACCOUNT_IN_BLACKLIST: "ACCOUNT_IN_BLACKLIST",
	USER_ALREADY_OWNS_NFT: "USER_ALREADY_OWNS_NFT",
	MESSAGE_NOT_SIGNED: "MESSAGE_NOT_SIGNED",
};

export const MINT_ERROR_CODES_TO_MESSAGES = {
	COMBINATION_TAKEN: "COMBINATION_TAKEN",
	ACCOUNT_IN_BLACKLIST: "ACCOUNT_IN_BLACKLIST",
	USER_ALREADY_OWNS_NFT: "USER_ALREADY_OWNS_NFT",
	MESSAGE_NOT_SIGNED: "MESSAGE_NOT_SIGNED",
};
